### ISSUE TITLE
Fitz Dark Italic theme not showing up

### ISSUE THREAD

**Issue by sheafitzek** [jschr/vscodethemes#115]
It is published in the [marketplace](https://marketplace.visualstudio.com/items?itemName=sheafitzek.fitz-dark-italic-vscode-theme) and the package.json includes:
```json
{
	...
	"repository": {
		"type": "git",
		"url": "https://github.com/sheafitzek/fitz-dark-italic-vscode-theme"
	},
	...
	"contributes": {
		"themes": [
			{
				"label": "Fitz Dark Italic",
				"uiTheme": "vs-dark",
				"path": "./themes/fitz-dark-italic-vscode-theme.json"
			}
		]
	},
	...
}
```
The theme definition is in .JSON format and both `colors` and `tokenColors` are defined.

**Comment by jschr** [comment]
This is the error that I'm seeing when trying to parse the theme: 

```
SyntaxError: Unexpected token } in JSON at position 29836
    at JSON.parse (<anonymous>)
    at run (evalmachine.<anonymous>:8:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

You can test it out here: https://repl.it/@jschr/fitz-dark-italic-vscode-theme

All I'm doing is stripping out comments and running `JSON.parse`.

**Comment by sheafitzek** [comment]
Thanks for the feedback. I'll have to try to debug it tomorrow evening.

**Comment by jschr** [comment]
Np, let me know what you find.

**Comment by sheafitzek** [comment]
Turns out I had a lot of hanging commas in my theme json. I wonder why the marketplace didn't throw any errors at me when I uploaded it. So are you pulling theme info for your site from the marketplace or github?

**Comment by jschr** [comment]
Thanks for digging into this.

I'm pulling it from github but I'd like to remove the github dependency and download extensions directly from the marketplace. Tracking that in https://github.com/jschr/vscodethemes/issues/93.

The marketplace isn't throwing an error because it's not trying to load the source of the theme. That happens in VSCode when the user installs the extension. My guess is VSCode is using `require` to load in the theme, which allows for comments and trailing commas.

I'm using `JSON.parse` because `require` is unsafe to use at the server. I'd like to find a way to remove trailing commas, just like I'm removing comments. Tracking that in https://github.com/jschr/vscodethemes/issues/123.

**Comment by sheafitzek** [comment]
My theme has been updated in the marketplace, along with my master branch. The repl.it linked above is no longer throwing errors, but I still don't see my theme on your site.

**Comment by jschr** [comment]
The sync only runs every 8 hours. I'm pushing through an update to strip trailing commas—I'll run it manually after https://github.com/jschr/vscodethemes/pull/124 is merged. Your theme will show up shortly after that.

**Comment by jschr** [comment]
https://vscodethemes.com/e/sheafitzek.fitz-dark-italic-vscode-theme

**Comment by sheafitzek** [comment]
I see it now. Thanks for all your help. You can close this one down now.
