### ISSUE TITLE
Search on every keystroke?

### ISSUE THREAD

**Issue by Haroenv** [jschr/vscodethemes#126]
Hey, just saw this being shared on Twitter, and was really impressed with the site. 

One thing I noticed is that the search is only done on keypress of enter, while usually in Algolia we can use search on every keypress (especially since now they are free with the QPS limit)

Did you use search on enter on purpose to limit the operations, not to go over the QPS limit or does it have another reason? 

Have a nice day!

**Comment by jschr** [comment]
Hey! Thanks for the kind words :-). Algolia is a pleasure to work with—can't recommend it enough. 

I had a search on keystroke version at the beginning but ultimately switch it for the on-enter for a couple reasons:
- Rendering all the theme previews on keystroke was noticeably less performant. Though I've since made some changes and this may not be an issue anymore.
- Messy analytics. I wanted to see what people we're searching for and by default I send a page view event on every update to the query string. As you can imagine this resulted in a lot of analytics events that were just partial searches. 

I can figure out the analytics issue other ways (I was just being lazy) so I may consider changing the behavior back to search on keystroke. 

I'll leave this issue open, I'm curious what others think here as well!

**Comment by Haroenv** [comment]
The analytics on Algolia’s side should deduplicate or take a “whole search” in account, but maybe sometimes it needs a bigger amount of searches to properly show it.

The rendering problem might still be there and i’d understand that reason. Maybe a debounce, with a value as low as you can afford could also be tried out?

**Comment by jschr** [comment]
Good point—I was looking at google analytics. Algolia's analytics will be more helpful there.

I'm going to play around with this again and see :-) 

Really appreciate the feedback.

**Comment by jschr** [comment]
Some progress on this captured here: https://github.com/jschr/vscodethemes/tree/search-on-keydown-attempt but more work required to finish and cleanup analytics. 

I'm not sold that this would be a better UX, or at least not worth the extra effort at the moment. 

This issue has been open a while so I'm going to close. I would consider re-opening it in the future.
