### ISSUE TITLE
Niketa theme is now Allegory

### ISSUE THREAD

**Issue by selfrefactor** [jschr/vscodethemes#141]
First, I want to thank you for the inclusion of my theme Niketa

I changed the direction and I cloned the old code to https://github.com/selfrefactor/allegory-theme which means that the link https://vscodethemes.com/search?q=niketa displays incorrect link. BTW feel free to check the screens of the new Niketa theme https://github.com/selfrefactor/niketa-theme as there are 7 light themes that you might find good enough for inclusion.

**Comment by jschr** [comment]
Hey, thanks for opening this issue. The syncing has been broken for at least a few weeks now and I didn't notice.

This should be fixed by https://github.com/jschr/vscodethemes/pull/143/commits/dd4d2cbc55523c0d1dd81a60236373684666c06c. I'll deploy the fix once I've confirmed your theme shows up in `dev` and https://github.com/jschr/vscodethemes/pull/143 is merged.

I also should be notified now if this ever happens again 😄

**Comment by jschr** [comment]
https://vscodethemes.com/e/selfrefactor.allegory-theme

**Comment by selfrefactor** [comment]
This is very nice indeed, thank you.
