### ISSUE TITLE
Is there a way to use your tokenizer/highlighter as a standalone solution?

### ISSUE THREAD

**Issue by isakkeyten** [jschr/vscodethemes#145]
I understand it's using vscode-textmate in the background, and considering vscode has the best syntax highlighting I've ever seen, I was browsing online looking for a solution to my problem.
After reading this blog post https://hackernoon.com/announcing-vscodethemes-4544f50c2b5b I gathered your website has tackled this problem before.

Any chance you might package your solution as a standalone vscode-textmate wrapper which uses vscode themes and their tokenizer?

**Comment by jschr** [comment]
hey @isakkeyten, 

The tokenizer is pretty close to a standalone package already: https://github.com/jschr/vscodethemes/tree/dev/tokenizer 

I can publish it to npm but I'm not sure if it will work for you as is. 

You can see how it's used here: https://github.com/jschr/vscodethemes/blob/dev/tokenizer/tests/themes.test.ts

It currently only tokenizes js, css and html but that could be made extensible. 

The entire module is only a little bit of code: https://github.com/jschr/vscodethemes/blob/dev/tokenizer/index.ts 

Could you elaborate on what you're looking for and how you'd like to use it? 

What value would this package provide for you instead of using [vscode-textmate](https://github.com/Microsoft/vscode-textmate) directly?

**Comment by isakkeyten** [comment]
I wanted to have an accurate server sided syntax highlighting using vscode themes for my project, which is sort of like a static website generator. I tried highlight.js, prisma.js and others, but was finding that themeing them according to vscode themes was being a hassle.
Was just wondering if there is an easy to use `vsCodeTextMateHighlight(code, theme)` solution readily available.
I'm not very well versed in typescript but I guess I can figure it out :)
Thanks for replying

**Comment by jschr** [comment]
https://github.com/Microsoft/vscode-textmate should help you get most of the way there.

With the code, language grammar and theme, it will output the tokenized code with the colors. 

You can see how I use it in this class: https://github.com/jschr/vscodethemes/blob/dev/tokenizer/index.ts#L22. I have the languages hardcoded to css, js and html. You'll also need a way to pass in the language grammar file. 

You can find the default language grammars in the the vscode repo, for example: https://github.com/Microsoft/vscode/tree/master/extensions/go/syntaxes

You can then render the tokenized code to html, for example: https://github.com/jschr/vscodethemes/blob/dev/tokenizer/tests/toHTML.ts

I'm happy to help answer any questions setting this up.

**Comment by jschr** [comment]
Going to close this. I probably won't be publishing the tokenizer as it's a thin wrapper around vscode-textmate. Might consider it in the future if there's value it can provide to others.

Happy to answer any questions as separate issues.
