### ISSUE TITLE
Search not working on iOS

### ISSUE THREAD

**Issue by Fasani** [jschr/vscodethemes#179]
Searching seems to do nothing and url looks malformed after pressing enter on iOS.

![image](https://user-images.githubusercontent.com/448410/83280842-79b27300-a1d7-11ea-9496-877ef90dca94.jpeg)

**Comment by ntrabue** [comment]
Hey @jschr I would love to contribute to your project if you're open to it. This is a really cool idea. I'm a front-end dev primarily and would like to help any way I can. If you're interested, I'd love some help getting a local build going.

I tried to open a branch to submit a PR but I don't have permissions. Hopefully this code snippet will suffice. You might want to test since I could only do so in a codesandbox. It looks like you aren't preventing the default form submission behavior on mobile devices causing a page refresh before your async logic can complete. Hope it helps!

```jsx
// frontend/utils/link.ts

export default function linkCallbackProps(
  router: SingletonRouter,
  href: UrlObject,
  as: UrlObject = href,
  resetScroll = true,
): LinkCallbackProps {
  return {
    href: createUrl(as),
    active: isUrlEqual(href, router),
    onClick: async (e: MouseEvent) => {
      // On mobile, specifically iOS, the history.push experience isn't great
      // out of the box. The scroll position doesn't reset when navigating and
      // you can't prevent background scroll on modals. More info on scroll
      // reseting in NextJS: https://github.com/zeit/next.js/issues/1309
      const isMobile = window.matchMedia(
        theme.breakpoints.mobile.replace('@media ', ''),
      ).matches
      
      // the default form submission event which forces a page reload was not being prevented on mobile devices
      e.preventDefault()

      if (isMobile) return

      // e.preventDefault()
      await router.push(href, as)
      if (resetScroll) {
        window.scrollTo(0, 0)
      }
    },
  }
}
```

**Comment by Fasani** [comment]
@ntrabue if you fork the repository first and then clone from your fork, you should be able to push the branch to GitHub to your personal GitHub account and from there open a PR.

**Comment by ntrabue** [comment]
Thank you @Fasani ill give that a shot after work. Is there any documentation or anything available for getting the project running locally? I've never used AWS stuff that wasn't pre-configured by my work. I can probably submit this PR without being able to run locally.
