### ISSUE TITLE
Xcode Partial (Dark) is deprecated

### ISSUE THREAD

**Issue by ConsciousClay** [jschr/vscodethemes#205]
Per [marketplace](https://marketplace.visualstudio.com/items?itemName=smockle.xcode-default-theme#review-details)

**Comment by jschr** [comment]
Are you expecting it to dissappear from vscodethemes.com?

Since the extension is still available on the marketplace it will still show up on the site. Unless there is a way to know if an extension is deprecated besides scanning the README I don't think there's much I can do to prevent it from showing.
