### ISSUE TITLE
VS Code for the Web: theme route

### ISSUE THREAD

**Issue by bamurtaugh** [jschr/vscodethemes#213]
:wave: Hi there! I'm Brigit, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

You can get a customized VS Code for the Web experience through unique `vscode.dev` URLs. You can share and experience themes through VS Code for the Web through the URL scheme: `https://vscode.dev/theme/extensionId`.

There is additional [info here](https://code.visualstudio.com/docs/editor/vscode-web#_themes) about this custom theme route.

We thought https://vscodethemes.com/ would be a great fit to include `vscode.dev/theme` URLs so that users can easily try out different themes. Perhaps an additional button to provide users the option to preview in desktop or the web?

Please let me know if you have any feedback, questions, or ideas - would love to discuss further. Thank you!

**Comment by jschr** [comment]
Hey @bamurtaugh, this is great! Ever since I first played around with vscode.dev I was hoping for this feature. Being able to preview a theme right from the browser sounds like an awesome experience, I will definitely look at adding the button very soon.

I read through the docs but I can't seem to get vscode.dev to open for a specific theme in the extension with `/theme/extensionId/themeName`. I tried [/theme/sdras.night-owl/Night Owl Light](https://vscode.dev/theme/sdras.night-owl/Night%20Owl%20Light) but I'm not quite sure what to set for `themeName`. Is that the correct usage?

I've been slowly working on the next version of the site which will let users search themes by color palette, add favourites and support for more languages. I'd be happy to chat more about what I've got planned and discuss any other ideas or feedback you might have as well. If you'd prefer to discuss outside of Github feel free to reach out to me at hello@jschr.io.

**Comment by jschr** [comment]
I just came across the theme preview featured in the [November 2021 updates](https://code.visualstudio.com/updates/v1_63). I would love for the ability to automatically open VSCode with a specific theme already selected to preview as well!

**Comment by bamurtaugh** [comment]
Thanks so much for the quick response, @jschr! Your usage is correct - I checked with my team, and we just implemented a change so that the URL structure you're trying (i.e. https://vscode.dev/theme/sdras.night-owl/Night%20Owl%20Light) should work now. Please let me know if you have any trouble. 

I'd love to chat more on your plans for the next version of the site. I'll send you an email to discuss!
